algorithm:
  pick_bias: 0.05
  random_seed: 2
  timelimit: 100
  walk_eps: 0.5
experiment:
  method: RW
  name: exp_0005
network:
  input_size: 10
  layer_num: 3
  layer_size: 10
  pruned_density: 0.8
